version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  
  node-app:
    build: .
    command: yarn dev
    environment:
      - PORT=3000
      - MONGO_USER=sanjeev
      - MONGO_PASSWORD=mypassword$$ythisyear
      - SESSION_SECRET=orwepfEWJAFAO@R@#R232jrifn3oq3
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
      - minio
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword$$ythisyear
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    volumes:
      - redis-data:/data
  
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  mongo-db:
  redis-data:
  minio-data:
